services:
  mysql:
    container_name: todo-app-db
    platform: linux/x86_64
    image: mysql:8.0.30
    env_file:
      - .env
    ports:
      - 3306:3306
  mongodb:
    container_name: mongodb
    image: mongo
    ports:
      - '27017:27017'
      
    environment:
      MONGO_INITDB_DATABASE: todo_app_mongodb
